const List<Map<String, String>> _kInventoryTrackerLegacySeedRows = [
  {
    'Product Name': 'Adjustable Backdrop',
    'QC Code': 'aadjustablebackdrop',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Ball Chain Metal',
    'QC Code': 'Aballchainmetal',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Balloon Stick',
    'QC Code': 'Aballoonstick',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Basahan',
    'QC Code': 'Abasahan',
    'Stock': '9880',
    'Maintaining': '2000 pcs',
    'Critical': '1000',
    'Total Quantity': '9880',
  },
  {
    'Product Name': 'Basket Net - Big',
    'QC Code': 'Abasketnetbig',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Basket Net - Small',
    'QC Code': 'Abasketnetsmall',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Binder Clip #2',
    'QC Code': 'Abinderclip2',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Bungee Rope 5mm',
    'QC Code': 'Abungeerope5mm',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'C2s 100',
    'QC Code': 'Ac2s#100',
    'Stock': '482',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '482',
  },
  {
    'Product Name': 'C2s 120',
    'QC Code': 'Ac2s#120',
    'Stock': '32',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '32',
  },
  {
    'Product Name': 'C2s 140',
    'QC Code': 'Ac2s#140',
    'Stock': '32',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '32',
  },
  {
    'Product Name': 'C2s 160',
    'QC Code': 'Ac2s#160',
    'Stock': '62',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '62',
  },
  {
    'Product Name': 'C2s 180',
    'QC Code': 'Ac2s#180',
    'Stock': '41',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '41',
  },
  {
    'Product Name': 'C2s 220',
    'QC Code': 'Ac2s#220',
    'Stock': '145',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '145',
  },
  {
    'Product Name': 'C2s 60',
    'QC Code': 'Ac2s#60',
    'Stock': '12',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '12',
  },
  {
    'Product Name': 'C2s 70',
    'QC Code': 'Ac2s#70',
    'Stock': '12',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '12',
  },
  {
    'Product Name': 'C2s 80',
    'QC Code': 'Ac2s#80',
    'Stock': '13',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Card Ring 3"',
    'QC Code': 'ACard Ring 3\'',
    'Stock': '50',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '50',
  },
  {
    'Product Name': 'Card Case A4',
    'QC Code': 'AcardcaseA4',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Card case A6',
    'QC Code': 'AcardcaseA6',
    'Stock': '1697',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1697',
  },
  {
    'Product Name': 'Card Case B4',
    'QC Code': 'AcardcaseB4',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Card Rind 1.5"',
    'QC Code': 'Acardring1.5',
    'Stock': '4',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Card Ring 3/4',
    'QC Code': 'Acardring3/4',
    'Stock': '19',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '19',
  },
  {
    'Product Name': 'Carton',
    'QC Code': 'Acarton',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Cellophane Clear',
    'QC Code': 'Acellophaneclear',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clay Cote 10',
    'QC Code': 'Aclaycote#10',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clay Cote 12',
    'QC Code': 'Aclaycote#12',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clay Cote 15',
    'QC Code': 'Aclaycote#15',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clay Cote 18',
    'QC Code': 'Aclaycote#18',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clay Cote 20',
    'QC Code': 'Aclaycote#20',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clay Cote 24',
    'QC Code': 'Aclaycote#24',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Clear PVC Sheet 5mm',
    'QC Code': 'Aclearpvcsheet.5mm',
    'Stock': '4',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Tranfering Tape Clear 24"',
    'QC Code': 'Acleartrasnfertape24"',
    'Stock': '90',
    'Maintaining': '10',
    'Critical': '0',
    'Total Quantity': '90',
  },
  {
    'Product Name': 'Clip Holder',
    'QC Code': 'Aclipholder',
    'Stock': '22',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '22',
  },
  {
    'Product Name': 'Cup Hool 1"',
    'QC Code': 'acuphook1"',
    'Stock': '50',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '50',
  },
  {
    'Product Name': 'Cutter Blade Small',
    'QC Code': 'Acutrblde-sml',
    'Stock': '233',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '233',
  },
  {
    'Product Name': 'Cutter Blade Big',
    'QC Code': 'AcutterBIG',
    'Stock': '228',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '228',
  },
  {
    'Product Name': 'Cutter Blade Pointed',
    'QC Code': 'Acutterpointed',
    'Stock': '20',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '20',
  },
  {
    'Product Name': 'Double Sided Tape 2"',
    'QC Code': 'ADouble Sided tape 2',
    'Stock': '172',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '172',
  },
  {
    'Product Name': 'Double Sided Tape 1"',
    'QC Code': 'Adoublesidedtape1"',
    'Stock': '9379',
    'Maintaining': '500 pcs',
    'Critical': '250',
    'Total Quantity': '9379',
  },
  {
    'Product Name': 'Double Sided Tape 1/2',
    'QC Code': 'Adoublesidedtape1/2',
    'Stock': '10',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'Easel Stand Metal',
    'QC Code': 'Aeselstand',
    'Stock': '15',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '15',
  },
  {
    'Product Name': 'Easel Stand Wood',
    'QC Code': 'AEaselStandWood',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Elastic Cord 1.5mm',
    'QC Code': 'Aelasticcord1.5mm',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Eyelet Big',
    'QC Code': 'Aeyelet#2',
    'Stock': '764',
    'Maintaining': '100 packs',
    'Critical': '50',
    'Total Quantity': '764',
  },
  {
    'Product Name': 'Eyelet Small',
    'QC Code': 'aeyeletsmall303',
    'Stock': '18',
    'Maintaining': '2 packs',
    'Critical': '1',
    'Total Quantity': '18',
  },
  {
    'Product Name': 'Foam Board 5mm',
    'QC Code': 'Afoambrd5',
    'Stock': '335',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '335',
  },
  {
    'Product Name': 'Foam Tape',
    'QC Code': 'Afoamtp',
    'Stock': '4224',
    'Maintaining': '500 pcs',
    'Critical': '250',
    'Total Quantity': '4224',
  },
  {
    'Product Name': 'Fold Coat 10',
    'QC Code': 'Afoldcote10',
    'Stock': '3708',
    'Maintaining': '500 pcs',
    'Critical': '250',
    'Total Quantity': '3708',
  },
  {
    'Product Name': 'Fold Coat 15',
    'QC Code': 'Afoldcote15',
    'Stock': '42',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '42',
  },
  {
    'Product Name': 'Fold Coat 20',
    'QC Code': 'Afoldcote20',
    'Stock': '1399',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '1399',
  },
  {
    'Product Name': 'Hi Impact sheet 1mm',
    'QC Code': 'ahips1mm4x8',
    'Stock': '72',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '72',
  },
  {
    'Product Name': 'ID Clip With Metal',
    'QC Code': 'Aidclipwithmetal',
    'Stock': '17100',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '17100',
  },
  {
    'Product Name': 'ID Hook Clip',
    'QC Code': 'Aidhookclip',
    'Stock': '68',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '68',
  },
  {
    'Product Name': 'ID Lace With Metal Hook',
    'QC Code': 'Aidlacewithmetalhook',
    'Stock': '901',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '901',
  },
  {
    'Product Name': 'Key Chain Ring',
    'QC Code': 'Akychnrng1"',
    'Stock': '54',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '54',
  },
  {
    'Product Name': 'Magnetic Glossy',
    'QC Code': 'Amagneticglossy',
    'Stock': '17',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '17',
  },
  {
    'Product Name': 'Magnetic Tag',
    'QC Code': 'Amagnetictag',
    'Stock': '15',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '15',
  },
  {
    'Product Name': 'Masking Tape 3/4',
    'QC Code': 'amaskingtape3/4',
    'Stock': '585',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '585',
  },
  {
    'Product Name': 'Nano Tape 1mm',
    'QC Code': 'Ananotape1mm',
    'Stock': '919',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '919',
  },
  {
    'Product Name': 'Nylon Rope 12mm',
    'QC Code': 'Anylonrop12',
    'Stock': '13',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Nylon Rope 6mm',
    'QC Code': 'Anylonrop6',
    'Stock': '67',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '67',
  },
  {
    'Product Name': 'Nylon Rope 3mm',
    'QC Code': 'Anylonrope3',
    'Stock': '5',
    'Maintaining': '1 roll',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Packing Tape Clear 2"',
    'QC Code': 'Apackaging Tape CLR 2',
    'Stock': '1992',
    'Maintaining': '300 pcs',
    'Critical': '250',
    'Total Quantity': '1992',
  },
  {
    'Product Name': 'Portable Booth PVC',
    'QC Code': 'Aportableboothpvc',
    'Stock': '256',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '256',
  },
  {
    'Product Name': 'Portable Booth Wood',
    'QC Code': 'Aportabothwood',
    'Stock': '11',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'PP Corrugated Board',
    'QC Code': 'APPBoard3mm',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'Pull Up Stand 3x6',
    'QC Code': 'Apullup3x6',
    'Stock': '28',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '28',
  },
  {
    'Product Name': 'Pull Up Stand 2x5',
    'QC Code': 'ApullupAL25',
    'Stock': '428',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '428',
  },
  {
    'Product Name': 'Pull Up Stand 2.75x6.5',
    'QC Code': 'ApullupAL26',
    'Stock': '4500',
    'Maintaining': '500 pcs',
    'Critical': '250',
    'Total Quantity': '4500',
  },
  {
    'Product Name': 'Pull Up Stand 2.75x6.5 Deluxe',
    'QC Code': 'ApullupAL26',
    'Stock': '0',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '0',
  },
  {
    'Product Name': 'Accetate',
    'QC Code': 'Apvccover(acetate)',
    'Stock': '9',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '9',
  },
  {
    'Product Name': 'PVC Rigid White 0.5mm',
    'QC Code': 'Apvcrigidwhite.5mm',
    'Stock': '124',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '124',
  },
  {
    'Product Name': 'PVC Rigid White 0.7mm',
    'QC Code': 'Apvcrigidwhite.7mm4x8',
    'Stock': '15',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '15',
  },
  {
    'Product Name': 'PVC Rigid White 1mm',
    'QC Code': 'Apvcrigidwhite1mm4x8',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Ring Small',
    'QC Code': 'Aringsmall',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Rubber Tips 1/2',
    'QC Code': 'Arubber tips 1/2',
    'Stock': '3000',
    'Maintaining': '1 pack',
    'Critical': '0',
    'Total Quantity': '3000',
  },
  {
    'Product Name': 'S-Hook Hanger 90mm',
    'QC Code': 'Ashookhanger90mm',
    'Stock': '6',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '6',
  },
  {
    'Product Name': 'Sintra 1.5mm',
    'QC Code': 'Asintra1.5',
    'Stock': '6720',
    'Maintaining': '300 pcs',
    'Critical': '150',
    'Total Quantity': '6720',
  },
  {
    'Product Name': 'Sintra 2mm',
    'QC Code': 'Asintra2',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Sintra 3mm',
    'QC Code': 'Asintra3',
    'Stock': '8259',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '8259',
  },
  {
    'Product Name': 'Sintra 3mm Black',
    'QC Code': 'Asintra3black',
    'Stock': '347',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '347',
  },
  {
    'Product Name': 'Sintra 3mm Red',
    'QC Code': 'Asintra3red',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Sintra 5mm',
    'QC Code': 'Asintra5',
    'Stock': '1657',
    'Maintaining': '100 pcs',
    'Critical': '100',
    'Total Quantity': '1657',
  },
  {
    'Product Name': 'Staple Wire #35',
    'QC Code': 'Astaplewire35',
    'Stock': '309',
    'Maintaining': '5 boxes',
    'Critical': '2',
    'Total Quantity': '309',
  },
  {
    'Product Name': 'Super Glue / Lactite',
    'QC Code': 'ASuperglue65g',
    'Stock': '1175',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '1175',
  },
  {
    'Product Name': 'Tansi',
    'QC Code': 'Atansi',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Tansi 0.70',
    'QC Code': 'Atansi.70',
    'Stock': '6',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '6',
  },
  {
    'Product Name': 'Tansi 0.80',
    'QC Code': 'Atansi.80',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Vanity Hook',
    'QC Code': 'Avanityhook',
    'Stock': '800',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '800',
  },
  {
    'Product Name': 'Velcro',
    'QC Code': 'avelcro125',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Vellum Paper 100',
    'QC Code': 'Avellumpaper100',
    'Stock': '23',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '23',
  },
  {
    'Product Name': 'Vellum Paper 120',
    'QC Code': 'Avellumpaper120',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'X-Stand 2.5x6',
    'QC Code': 'Axstand2.5x6',
    'Stock': '235',
    'Maintaining': '30 pcs',
    'Critical': '15',
    'Total Quantity': '235',
  },
  {
    'Product Name': 'X-Stand 2x5',
    'QC Code': 'Axstand2x5',
    'Stock': '380',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '380',
  },
  {
    'Product Name': 'Xtreme Pull Up 3meter',
    'QC Code': 'Axtrmepullup 3m',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Yarn',
    'QC Code': 'Ayarn',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Ziplock',
    'QC Code': 'Aziplock',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Angle Bar 1x1 2mm',
    'QC Code': 'Fabar1118',
    'Stock': '170',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '170',
  },
  {
    'Product Name': 'Angle Bar 1.5x1.5 2mm',
    'QC Code': 'Fabar1121126',
    'Stock': '34',
    'Maintaining': '5 pcs',
    'Critical': '2',
    'Total Quantity': '34',
  },
  {
    'Product Name': 'Acrylic Primer Gray',
    'QC Code': 'Facprimergray',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Acrylic Paint',
    'QC Code': 'facrylcpaint',
    'Stock': '9',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '9',
  },
  {
    'Product Name': 'Acrylic Thinner - Anzahl',
    'QC Code': 'Facrylcthner',
    'Stock': '31',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '31',
  },
  {
    'Product Name': 'Acrylic Black 3mm',
    'QC Code': 'FAcrylic black 3mm',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Acrylic Clear 1.5mm',
    'QC Code': 'Facrylic15',
    'Stock': '137',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '137',
  },
  {
    'Product Name': 'Acrylic Blue 1.5mm',
    'QC Code': 'Facrylic15blue',
    'Stock': '20',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '20',
  },
  {
    'Product Name': 'Acrylic Clear 3mm',
    'QC Code': 'Facrylicc348',
    'Stock': '111',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '111',
  },
  {
    'Product Name': 'Acrylic Colored 3mm ',
    'QC Code': 'Facrylicc348colored',
    'Stock': '17',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '17',
  },
  {
    'Product Name': 'Acrylic Colored 4mm ',
    'QC Code': 'Facrylicc448',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Acrylic Diffuser White 5mm',
    'QC Code': 'facrylicdiffuserwhite5mm',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Acrylic Glue',
    'QC Code': 'facrylicglue',
    'Stock': '25',
    'Maintaining': '2 pcs/bottles',
    'Critical': '1',
    'Total Quantity': '25',
  },
  {
    'Product Name': 'Acrylic Paint Jet Black',
    'QC Code': 'Facrylicpaintjetblack',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Aluminum Composit',
    'QC Code': 'Falumcomp',
    'Stock': '14',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '14',
  },
  {
    'Product Name': 'Aluminum Tube 1/2',
    'QC Code': 'FAluminum Tube1/2',
    'Stock': '260',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '260',
  },
  {
    'Product Name': 'Aluminum Angle 1x1x21',
    'QC Code': 'FAluminumangle1x1x21',
    'Stock': '14',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '14',
  },
  {
    'Product Name': 'Aluminum Angle 1 1/2x1x21',
    'QC Code': 'FAluminumUchanel11/2x21ft',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Ball Bearing',
    'QC Code': 'Fballbearing',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'BI Pipe',
    'QC Code': 'Fbipipe2',
    'Stock': '5',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Black Screw Metal 1',
    'QC Code': 'Fblackscrewmetal1',
    'Stock': '1100',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '1100',
  },
  {
    'Product Name': 'Black Screw Metal 2',
    'QC Code': 'Fblackscrewmetal2',
    'Stock': '416',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '416',
  },
  {
    'Product Name': 'Black Screw Wood 1',
    'QC Code': 'Fblackscrewwood1',
    'Stock': '1731',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '1731',
  },
  {
    'Product Name': 'Black Screw Wood 1 1/2',
    'QC Code': 'FBlackscrewWood11/2',
    'Stock': '150',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '150',
  },
  {
    'Product Name': 'Black Screw Wood 2',
    'QC Code': 'Fblackscrewwood2',
    'Stock': '963',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '963',
  },
  {
    'Product Name': 'Black Screw Wood 3',
    'QC Code': 'Fblackscrewwood3',
    'Stock': '396',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '396',
  },
  {
    'Product Name': 'Blind Rivet 812',
    'QC Code': 'Fblindrivet1812',
    'Stock': '25',
    'Maintaining': '5 boxes',
    'Critical': '3',
    'Total Quantity': '25',
  },
  {
    'Product Name': 'Blind Rivet 834',
    'QC Code': 'Fblindrivet1834',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Blind Rivet 858',
    'QC Code': 'Fblindrivet1858',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Bolts & Nuts 1/4x1 1/2',
    'QC Code': 'Fbolts&nut1/4x1 1/2',
    'Stock': '30',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '30',
  },
  {
    'Product Name': 'Bolts & Nuts 1/4x1/2',
    'QC Code': 'Fbolts&nut1/4x1/2',
    'Stock': '8',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '8',
  },
  {
    'Product Name': 'Bolts & Nuts 1/4x3/4',
    'QC Code': 'Fbolts&nut1/4x3/4',
    'Stock': '100',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '100',
  },
  {
    'Product Name': 'Bolts & Nuts 4x20',
    'QC Code': 'Fboltsandnuts4x20',
    'Stock': '120',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '120',
  },
  {
    'Product Name': 'Bolts & Nuts 4x40',
    'QC Code': 'Fboltsandnuts4x40',
    'Stock': '20',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '20',
  },
  {
    'Product Name': 'Bolts & Nuts 4x50',
    'QC Code': 'Fboltsandnuts4x50',
    'Stock': '60',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '60',
  },
  {
    'Product Name': 'Bolts & Nuts 4x60',
    'QC Code': 'FboltsandnutsM4x60',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Bostik (no more nail)',
    'QC Code': 'Fbostiknomorenail',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Cable tie 6"',
    'QC Code': 'Fcable tie white 6"(150mm)',
    'Stock': '254',
    'Maintaining': '1 pack',
    'Critical': '0',
    'Total Quantity': '254',
  },
  {
    'Product Name': 'Cable tie 12"',
    'QC Code': 'Fcabletie 12"',
    'Stock': '1',
    'Maintaining': '1 pack',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Cement',
    'QC Code': 'Fcement',
    'Stock': '13',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Chain',
    'QC Code': 'Fchain',
    'Stock': '108',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '108',
  },
  {
    'Product Name': 'Chalk Stone',
    'QC Code': 'Fchalkstone',
    'Stock': '19',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '19',
  },
  {
    'Product Name': 'Acrylic Clear 5mm',
    'QC Code': 'Fclearacrylic5mm',
    'Stock': '4',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Sealant Clear',
    'QC Code': 'Fclrsealant',
    'Stock': '98',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '98',
  },
  {
    'Product Name': 'Common Nail 1 1/2',
    'QC Code': 'Fcommonnail1 1/2',
    'Stock': '3',
    'Maintaining': '1 box',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'Common Nail 2',
    'QC Code': 'Fcommonnail2',
    'Stock': '8',
    'Maintaining': '2 kilos',
    'Critical': '1',
    'Total Quantity': '8',
  },
  {
    'Product Name': 'Common Nail 3',
    'QC Code': 'Fcommonnail3',
    'Stock': '37',
    'Maintaining': '3 kilos',
    'Critical': '1',
    'Total Quantity': '37',
  },
  {
    'Product Name': 'Connecting Screw',
    'QC Code': 'fconnectingscew',
    'Stock': '10',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'Cotton Gloves',
    'QC Code': 'Fcottongloves',
    'Stock': '24',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '24',
  },
  {
    'Product Name': 'Cutting Disk 12',
    'QC Code': 'Fcuttingdisk12',
    'Stock': '13',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Cutting disk 4',
    'QC Code': 'Fcuttingdisk4',
    'Stock': '132',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '132',
  },
  {
    'Product Name': 'Deform Bar 20',
    'QC Code': 'Fdefrmrb20',
    'Stock': '11',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'Acrylic Diffuser White 3mm',
    'QC Code': 'Fdiffwhite3',
    'Stock': '21',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '21',
  },
  {
    'Product Name': 'Acrylic Diffuser White 4mm',
    'QC Code': 'Fdiffwhite4',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Drill Bit 5/16',
    'QC Code': 'FDrillbit 5/16',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Drill Bit 1/8',
    'QC Code': 'FDrillbit1/8',
    'Stock': '30',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '30',
  },
  {
    'Product Name': 'Drill Bit 1/4',
    'QC Code': 'Fdrillbit14',
    'Stock': '2',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Drill Bit 3/16',
    'QC Code': 'Fdrillbit316',
    'Stock': '4',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Drill Bit 3/8',
    'QC Code': 'Fdrillbit38',
    'Stock': '7',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'Drill Bit 9/64',
    'QC Code': 'Fdrillbit9/64',
    'Stock': '222',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '222',
  },
  {
    'Product Name': 'Duct Tape',
    'QC Code': 'Fducttape',
    'Stock': '16',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '16',
  },
  {
    'Product Name': 'Electric Tape',
    'QC Code': 'Felectricaltape',
    'Stock': '13',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Epory Primer Gray w/ Catalyst',
    'QC Code': 'FepxyprimerGRAYw/catalyst',
    'Stock': '19',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '19',
  },
  {
    'Product Name': 'Flat Bar 1x6m',
    'QC Code': 'Fflatbar1',
    'Stock': '4',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Flat Bar 2x6m',
    'QC Code': 'Fflatbar2',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Flat Bar 3/4x6m',
    'QC Code': 'Fflatbar3/4',
    'Stock': '14',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '14',
  },
  {
    'Product Name': 'GI Sheet 16',
    'QC Code': 'Fgisheet16',
    'Stock': '2',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'GI Sheet 18',
    'QC Code': 'Fgisheet18',
    'Stock': '23',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '23',
  },
  {
    'Product Name': 'GI Sheet 24',
    'QC Code': 'Fgisheet24',
    'Stock': '4',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'GI Sheet 26',
    'QC Code': 'Fgisheet26',
    'Stock': '20',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '20',
  },
  {
    'Product Name': 'GI Wire #16',
    'QC Code': 'Fgiwire16',
    'Stock': '33',
    'Maintaining': ' 30 kilos',
    'Critical': '1',
    'Total Quantity': '33',
  },
  {
    'Product Name': 'Glass Clip 1/4',
    'QC Code': 'Fglassclip1/4',
    'Stock': '27',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '27',
  },
  {
    'Product Name': 'Gravel',
    'QC Code': 'Fgravel',
    'Stock': '85',
    'Maintaining': '5 sacks',
    'Critical': '2',
    'Total Quantity': '85',
  },
  {
    'Product Name': 'Grinding Disc',
    'QC Code': 'fgrindingdisc4',
    'Stock': '14',
    'Maintaining': '5 pcs',
    'Critical': '2',
    'Total Quantity': '14',
  },
  {
    'Product Name': 'Hack Saw Blade',
    'QC Code': 'Fhacksawblade',
    'Stock': '10',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'Hanging Cord',
    'QC Code': 'Fhangingcord',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Hardener Big',
    'QC Code': 'Fhardenerbig',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'Hook & Eye',
    'QC Code': 'FHook&Eye',
    'Stock': '10',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'Joy Diswashing',
    'QC Code': 'Fjoy',
    'Stock': '218',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '218',
  },
  {
    'Product Name': 'Lag Screw',
    'QC Code': 'Flagscrew',
    'Stock': '45',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '45',
  },
  {
    'Product Name': 'Lag Screw w/ Shied 3/8x2 1/12',
    'QC Code': 'Flagscreww/shield 3/8x2 1/2',
    'Stock': '45',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '45',
  },
  {
    'Product Name': 'Lazy Susan 4"',
    'QC Code': 'Flazysusan4in',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Led Strip DC 12v',
    'QC Code': 'Fledstripdc12V',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'McCal Sticker',
    'QC Code': 'Fmccalsticker',
    'Stock': '98',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '98',
  },
  {
    'Product Name': 'Nichrome Wire 1500w',
    'QC Code': 'fnichromewire1500w',
    'Stock': '13',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Nuts 3/8',
    'QC Code': 'FNuts 3/8',
    'Stock': '40',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '40',
  },
  {
    'Product Name': 'Paint Brush 2',
    'QC Code': 'Fpaintbrush2',
    'Stock': '21',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '21',
  },
  {
    'Product Name': 'Paint Roller Cotton',
    'QC Code': 'Fpaintrollercotton',
    'Stock': '13',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Paint Roller Foam',
    'QC Code': 'Fpaintrollerfoam',
    'Stock': '17',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '17',
  },
  {
    'Product Name': 'Paint Thinner',
    'QC Code': 'Fpaintthnnr',
    'Stock': '8',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '8',
  },
  {
    'Product Name': 'Paleta Big',
    'QC Code': 'Fpaletabig',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Plywood 1/2',
    'QC Code': 'Fplywood1/2',
    'Stock': '6',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '6',
  },
  {
    'Product Name': 'Plywood 1/4',
    'QC Code': 'Fplywood1/4',
    'Stock': '7',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'Plywood 3/4',
    'QC Code': 'Fplywood3/4',
    'Stock': '20',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '20',
  },
  {
    'Product Name': 'Poly Top Hardener',
    'QC Code': 'Fpolytffhardener',
    'Stock': '9',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '9',
  },
  {
    'Product Name': 'Puwer Supply 100',
    'QC Code': 'Fpowersupply100',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'Rectangular Tube BI ',
    'QC Code': 'frectangulartubeBI1x2',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Roler Refill',
    'QC Code': 'Frolerrefill',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Sand',
    'QC Code': 'Fsand',
    'Stock': '134',
    'Maintaining': '5 sacks',
    'Critical': '3',
    'Total Quantity': '134',
  },
  {
    'Product Name': 'Sanding Disc',
    'QC Code': 'fsandingdisc4',
    'Stock': '47',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '47',
  },
  {
    'Product Name': 'Sand Paper #280',
    'QC Code': 'FSandpaper #280',
    'Stock': '50',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '50',
  },
  {
    'Product Name': 'Sand Paper #1000',
    'QC Code': 'Fsandpaper#1000',
    'Stock': '24',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '24',
  },
  {
    'Product Name': 'Sand Paper #120',
    'QC Code': 'Fsandpaper#120',
    'Stock': '118',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '118',
  },
  {
    'Product Name': 'Sand Paper #60',
    'QC Code': 'Fsandpaper60',
    'Stock': '122',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '122',
  },
  {
    'Product Name': 'Sand Paper #240',
    'QC Code': 'Fsandppr240',
    'Stock': '33',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '33',
  },
  {
    'Product Name': 'Sand Paper #80',
    'QC Code': 'Fsandppr80',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Signage Screw',
    'QC Code': 'Fsignagescrew',
    'Stock': '736',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '736',
  },
  {
    'Product Name': 'Signage Screw 12x22',
    'QC Code': 'FSignageScw 12x22',
    'Stock': '510',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '510',
  },
  {
    'Product Name': 'Solid Wire',
    'QC Code': 'Fslidwre',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Speaker Wire',
    'QC Code': 'Fspkrwire18',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'Spot Putty White',
    'QC Code': 'Fspotputtywhite',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Spring w/ Hook',
    'QC Code': 'fspringwithhook',
    'Stock': '8',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '8',
  },
  {
    'Product Name': 'Square Tube 1.5x1.5x20',
    'QC Code': 'Fsquaretube1.5x1.5x20 1.2mm',
    'Stock': '7',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'Square Tube 1x1x20',
    'QC Code': 'Fsquaretube1x1x20 1.2mm',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Stickwel Wood Glue',
    'QC Code': 'Fstickwell',
    'Stock': '6',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '6',
  },
  {
    'Product Name': 'Stranded Wire',
    'QC Code': 'FStrndedWire12',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'Suction Cap',
    'QC Code': 'fsuctioncap',
    'Stock': '216',
    'Maintaining': '10 packs',
    'Critical': '5',
    'Total Quantity': '216',
  },
  {
    'Product Name': 'T8 Led Tube Light ',
    'QC Code': 'ft84ft18w',
    'Stock': '104',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '104',
  },
  {
    'Product Name': 'Tekscrew Metal 1',
    'QC Code': 'Ftekscrewmetal1in',
    'Stock': '740',
    'Maintaining': '100 pcs',
    'Critical': '50',
    'Total Quantity': '740',
  },
  {
    'Product Name': 'Tekscrew Metal 2',
    'QC Code': 'Ftekscrewmetal2in',
    'Stock': '232',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '232',
  },
  {
    'Product Name': 'Tekscrew Metal 3',
    'QC Code': 'Ftekscrewmetal3in',
    'Stock': '167',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '167',
  },
  {
    'Product Name': 'Tekscrew Wood 1',
    'QC Code': 'Ftekscrewwood1in',
    'Stock': '150',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '150',
  },
  {
    'Product Name': 'Tekscrew Wood 2',
    'QC Code': 'Ftekscrewwood2in',
    'Stock': '200',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '200',
  },
  {
    'Product Name': 'Tekscrew Wood 3',
    'QC Code': 'Ftekscrewwood3in',
    'Stock': '4',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Thinner',
    'QC Code': 'Fthinner',
    'Stock': '13',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Lumber 2x2 10ft',
    'QC Code': 'Flumber 2x2x10 SD',
    'Stock': '70',
    'Maintaining': '10',
    'Critical': '0',
    'Total Quantity': '70',
  },
  {
    'Product Name': 'Lumber 2x2 12ft',
    'QC Code': 'Flumber 2x2x12 SD',
    'Stock': '179',
    'Maintaining': '20',
    'Critical': '0',
    'Total Quantity': '179',
  },
  {
    'Product Name': 'Threaded Rod',
    'QC Code': 'FThreadedRod',
    'Stock': '24',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '24',
  },
  {
    'Product Name': 'Topcoat Anzhal',
    'QC Code': 'Ftopcoat-anzhal',
    'Stock': '14',
    'Maintaining': '3 pcs',
    'Critical': '1',
    'Total Quantity': '14',
  },
  {
    'Product Name': 'Tox',
    'QC Code': 'Ftox',
    'Stock': '100',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '100',
  },
  {
    'Product Name': 'Tox 6',
    'QC Code': 'Ftox6',
    'Stock': '900',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '900',
  },
  {
    'Product Name': 'Transfer tape 12',
    'QC Code': 'Ftransfertape12',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Triangle Hook',
    'QC Code': 'FTriangleHook',
    'Stock': '100',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '100',
  },
  {
    'Product Name': 'Wall Putty ',
    'QC Code': 'FwallputtyBosny',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Washer',
    'QC Code': 'Fwasher',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Welding Rod 3/32',
    'QC Code': 'Fweldingrod3/32 N6013 2.5mm',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Welding Rod 5/64',
    'QC Code': 'Fweldingrod5/64',
    'Stock': '10',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'White Board 4x6\'',
    'QC Code': 'fwhiteboard',
    'Stock': '3',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '3',
  },
  {
    'Product Name': 'White Board 3x4\'',
    'QC Code': 'fwhiteboard3x4ft',
    'Stock': '7',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'Rubber Caster Wheel',
    'QC Code': 'Fwhlcaster',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Wipe Out',
    'QC Code': 'Fwipeout',
    'Stock': '11',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'Backlit 36"',
    'QC Code': 'Ibklt836',
    'Stock': '7',
    'Maintaining': '1 roll',
    'Critical': '0',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'Backlit 50"',
    'QC Code': 'Ibklt850',
    'Stock': '51',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '51',
  },
  {
    'Product Name': 'Backlit 60"',
    'QC Code': 'Ibklt860',
    'Stock': '13',
    'Maintaining': '1 roll',
    'Critical': '0',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Canvass 50"',
    'QC Code': 'Icanvass50',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Double Adhesive Film 36"',
    'QC Code': 'Idbleadh36',
    'Stock': '18',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '18',
  },
  {
    'Product Name': 'Double Adhesive Film 50"',
    'QC Code': 'Idbleadh50',
    'Stock': '24',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '24',
  },
  {
    'Product Name': 'Double Adhesive Film 60"',
    'QC Code': 'Idbleadh60',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Epson Ink - Black',
    'QC Code': 'IEpsonBlck',
    'Stock': '117',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '117',
  },
  {
    'Product Name': 'Epson Cleaning Cartridge',
    'QC Code': 'IEpsonCleaningCartridge',
    'Stock': '51',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '51',
  },
  {
    'Product Name': 'Epson Ink - Cyan',
    'QC Code': 'IEpsonCyn',
    'Stock': '206',
    'Maintaining': '30 pcs',
    'Critical': '15',
    'Total Quantity': '206',
  },
  {
    'Product Name': 'Epson Ink - Light Black',
    'QC Code': 'IEpsonLtBlck',
    'Stock': '63',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '63',
  },
  {
    'Product Name': 'Epson Ink - Light Cyan',
    'QC Code': 'IEpsonLtCyn',
    'Stock': '179',
    'Maintaining': '30 pcs',
    'Critical': '15',
    'Total Quantity': '179',
  },
  {
    'Product Name': 'Epson Ink - Light Magenta',
    'QC Code': 'IEpsonLtMgnta',
    'Stock': '171',
    'Maintaining': '30 pcs',
    'Critical': '15',
    'Total Quantity': '171',
  },
  {
    'Product Name': 'Epson Ink - Magenta',
    'QC Code': 'IEpsonMgnta',
    'Stock': '176',
    'Maintaining': '30 pcs',
    'Critical': '15',
    'Total Quantity': '176',
  },
  {
    'Product Name': 'Epson Ink - Orange',
    'QC Code': 'IEpsonOrnge',
    'Stock': '64',
    'Maintaining': '10 pcs',
    'Critical': '5',
    'Total Quantity': '64',
  },
  {
    'Product Name': 'Epson Maintenance Kit',
    'QC Code': 'IEpsonpartskit',
    'Stock': '24',
    'Maintaining': '5 pcs',
    'Critical': '3',
    'Total Quantity': '24',
  },
  {
    'Product Name': 'Epson Ink - Red',
    'QC Code': 'IEpsonRed',
    'Stock': '98',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '98',
  },
  {
    'Product Name': 'Epson Ink - White',
    'QC Code': 'IEpsonWhte',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Epson Ink - Yellow',
    'QC Code': 'IEpsonYllw',
    'Stock': '136',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '136',
  },
  {
    'Product Name': 'Glow in the Dark',
    'QC Code': 'Iglowinginthedark',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Gloss Lamination 36"',
    'QC Code': 'Iglslam36',
    'Stock': '4',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Gloss Lamination 42"',
    'QC Code': 'Iglslam42',
    'Stock': '9',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '9',
  },
  {
    'Product Name': 'Gloss Lamination 50"',
    'QC Code': 'Iglslam50',
    'Stock': '260',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '260',
  },
  {
    'Product Name': 'Gloss Lamination 54"',
    'QC Code': 'Iglslam54',
    'Stock': '20',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '20',
  },
  {
    'Product Name': 'Gloss Lamination 60"',
    'QC Code': 'Iglslam60',
    'Stock': '6',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '6',
  },
  {
    'Product Name': 'Graphtec Blade Cb09',
    'QC Code': 'IgraphtecbladeCB09',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Graphtec Blade Cb09-24',
    'QC Code': 'IgraphtecbladeCB0945',
    'Stock': '10',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'High Gloss Sticker',
    'QC Code': 'Ihighglosssticker',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Hologram 4.5ft',
    'QC Code': 'Ihologram4.5ft',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'JWEI Blade 311',
    'QC Code': 'IJweiBladecutting311',
    'Stock': '120',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '120',
  },
  {
    'Product Name': 'JWEI Blade 341',
    'QC Code': 'IJweiBladecutting341',
    'Stock': '11',
    'Maintaining': '2 pcs',
    'Critical': '1',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'JWEI Blade 603',
    'QC Code': 'IJweiBladecutting603',
    'Stock': '158',
    'Maintaining': '30 pcs',
    'Critical': '15',
    'Total Quantity': '158',
  },
  {
    'Product Name': 'Matte Lamination 36"',
    'QC Code': 'Imatlam36',
    'Stock': '34',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '34',
  },
  {
    'Product Name': 'Matte Lamination 42"',
    'QC Code': 'Imatlam42',
    'Stock': '71',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '71',
  },
  {
    'Product Name': 'Matte Lamination 50"',
    'QC Code': 'Imatlam50',
    'Stock': '778',
    'Maintaining': '20 rolls',
    'Critical': '10',
    'Total Quantity': '778',
  },
  {
    'Product Name': 'Matte Lamination 54"',
    'QC Code': 'Imatlam54',
    'Stock': '4',
    'Maintaining': '1 roll',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Matte Lamination 60"',
    'QC Code': 'Imatlam60',
    'Stock': '87',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '87',
  },
  {
    'Product Name': 'Outdoor Sticker Clear 54"',
    'QC Code': 'Ioclrstkr54',
    'Stock': '16',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '16',
  },
  {
    'Product Name': 'Outdoor Sticker Clear Matte 50"',
    'QC Code': 'Ioclrstkrmatte50',
    'Stock': '12',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '12',
  },
  {
    'Product Name': 'Outdoor Sticker Clear Matte 54"',
    'QC Code': 'Ioclrstkrmatte54',
    'Stock': '4',
    'Maintaining': '1 roll',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Outdoor Sticker Clear Matte 60"',
    'QC Code': 'Ioclrstkrmatte60',
    'Stock': '2',
    'Maintaining': ' 1 roll',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Outdoor Sticker Gloss 36"',
    'QC Code': 'Iovsgloss36',
    'Stock': '16',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '16',
  },
  {
    'Product Name': 'Outdoor Sticker Gloss 42"',
    'QC Code': 'Iovsgloss42',
    'Stock': '56',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '56',
  },
  {
    'Product Name': 'Outdoor Sticker Gloss 50"',
    'QC Code': 'Iovsgloss50',
    'Stock': '533',
    'Maintaining': '30 rolls',
    'Critical': '15',
    'Total Quantity': '533',
  },
  {
    'Product Name': 'Outdoor Sticker Gloss 54"',
    'QC Code': 'Iovsgloss54',
    'Stock': '214',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '214',
  },
  {
    'Product Name': 'Outdoor Sticker Gloss 60"',
    'QC Code': 'Iovsgloss60',
    'Stock': '34',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '34',
  },
  {
    'Product Name': 'Outdoor Sticker Matte 50"',
    'QC Code': 'Iovsmatte50',
    'Stock': '10',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '10',
  },
  {
    'Product Name': 'Outdoor Sticker Matte 54"',
    'QC Code': 'Iovsmatte54',
    'Stock': '7',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'Outdoor Sticker Matte 60"',
    'QC Code': 'Iovsmatte60',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Media Intect Sticker Gloss 54"',
    'QC Code': 'Imediaintecstckgloss',
    'Stock': '36',
    'Maintaining': '5',
    'Critical': '3',
    'Total Quantity': '36',
  },
  {
    'Product Name': 'Perforated Sticker',
    'QC Code': 'Iperforated',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Satin Sticker',
    'QC Code': 'Isatinsticker',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Blackout 15oz 10.5ft',
    'QC Code': 'Oblk15126',
    'Stock': '116',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '116',
  },
  {
    'Product Name': 'Blackout 15oz 8.2ft',
    'QC Code': 'Oblk158.2',
    'Stock': '14',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '14',
  },
  {
    'Product Name': 'Blackout 15oz 9.2ft',
    'QC Code': 'Oblk159.2blackback',
    'Stock': '4',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Blackout 18oz 10.5ft',
    'QC Code': 'Oblk18oz 50m',
    'Stock': '104',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '104',
  },
  {
    'Product Name': 'Blackout 21oz 10.5ft',
    'QC Code': 'Oblk21oz 50m',
    'Stock': '84',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '84',
  },
  {
    'Product Name': 'ECO Solvent Photo Paper Matte 36"',
    'QC Code': 'OEcoSlvnt PP Matte 36"',
    'Stock': '11',
    'Maintaining': '1 roll',
    'Critical': '0',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'ECO Solvent Photo Paper Matte 50"',
    'QC Code': 'OEcoSlvnt PP matte 50"',
    'Stock': '28',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '28',
  },
  {
    'Product Name': 'ECO Solvent Photo Paper Matte 60"',
    'QC Code': 'OEcoSlvnt PP matte 60"',
    'Stock': '89',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '89',
  },
  {
    'Product Name': 'ECO Solvent Photo Paper Gloss 60"',
    'QC Code': 'OEcoSlvntPGSGloss50"',
    'Stock': '11',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'ECO Solvent PMS  36"',
    'QC Code': 'OEcoSlvntPMS 36"',
    'Stock': '23',
    'Maintaining': '3 rolls',
    'Critical': '1',
    'Total Quantity': '23',
  },
  {
    'Product Name': 'ECO Solvent PMS  42"',
    'QC Code': 'OEcoSlvntPMS 42"',
    'Stock': '54',
    'Maintaining': '3 rolls',
    'Critical': '1',
    'Total Quantity': '54',
  },
  {
    'Product Name': 'ECO Solvent PMS  50"',
    'QC Code': 'OEcoSlvntPMS 50" matte',
    'Stock': '1005',
    'Maintaining': '20 rolls',
    'Critical': '10',
    'Total Quantity': '1005',
  },
  {
    'Product Name': 'ECO Solvent PMS  60"',
    'QC Code': 'OEcoSlvntPMS 60"',
    'Stock': '13',
    'Maintaining': '2 rolls',
    'Critical': '1',
    'Total Quantity': '13',
  },
  {
    'Product Name': 'Flex Tarp 10.5ft',
    'QC Code': 'Oflex105',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Floor Lamination',
    'QC Code': 'ofloorlamination',
    'Stock': '4',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '4',
  },
  {
    'Product Name': 'Guntacker Staple Wire',
    'QC Code': 'Oguntackerwire',
    'Stock': '107',
    'Maintaining': '10 boxes',
    'Critical': '5',
    'Total Quantity': '107',
  },
  {
    'Product Name': 'GZ Blue Solution',
    'QC Code': 'Ogzbluesolution',
    'Stock': '7',
    'Maintaining': '3 bottles',
    'Critical': '1',
    'Total Quantity': '7',
  },
  {
    'Product Name': 'GZ Capping Moisturizer',
    'QC Code': 'Ogzcappingmoisturizer',
    'Stock': '25',
    'Maintaining': '5 bottles',
    'Critical': '3',
    'Total Quantity': '25',
  },
  {
    'Product Name': 'Job Out Intallation',
    'QC Code': 'Ojoboutinstlltn',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Metal Hinges',
    'QC Code': 'Ometalhinges',
    'Stock': '12',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '12',
  },
  {
    'Product Name': 'Outdoor Sticker 3M IJ220',
    'QC Code': 'Ooutdoorstckr 3M IJ220',
    'Stock': '77',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '77',
  },
  {
    'Product Name': 'Reflectorized Sticker - Plain Silver',
    'QC Code': 'OReflectorizedSticker4.1\'Plain',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Reflectorized Tarp 10.5ft',
    'QC Code': 'Oreflectorizedtarp5',
    'Stock': '15',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '15',
  },
  {
    'Product Name': 'Lumber 1x2 10ft',
    'QC Code': 'Orolumber1x2x10',
    'Stock': '1864',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '1864',
  },
  {
    'Product Name': 'Lumber 1x2 12ft',
    'QC Code': 'Orolumber1x2x12',
    'Stock': '1961',
    'Maintaining': '200 pcs',
    'Critical': '100',
    'Total Quantity': '1961',
  },
  {
    'Product Name': 'Lumber 1x1 10ft',
    'QC Code': 'Os4slumber1x1x10',
    'Stock': '420',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '420',
  },
  {
    'Product Name': 'Lumber 1x1 12ft',
    'QC Code': 'Os4slumber1x1x12',
    'Stock': '1684',
    'Maintaining': '50 pcs',
    'Critical': '25',
    'Total Quantity': '1684',
  },
  {
    'Product Name': 'GZ Ink - Cyan',
    'QC Code': 'Osgs2inkC',
    'Stock': '337',
    'Maintaining': '50 bottles',
    'Critical': '25',
    'Total Quantity': '337',
  },
  {
    'Product Name': 'GZ Ink - Black',
    'QC Code': 'Osgs2inkK',
    'Stock': '117',
    'Maintaining': '20 bottles',
    'Critical': '10',
    'Total Quantity': '117',
  },
  {
    'Product Name': 'GZ Ink - Magenta',
    'QC Code': 'Osgs2inkM',
    'Stock': '583',
    'Maintaining': '100 bottles',
    'Critical': '50',
    'Total Quantity': '583',
  },
  {
    'Product Name': 'GZ Ink - Yellow',
    'QC Code': 'Osgs2inkY',
    'Stock': '485',
    'Maintaining': '80 bottles',
    'Critical': '40',
    'Total Quantity': '485',
  },
  {
    'Product Name': 'GZ Solution',
    'QC Code': 'Osgs2solution',
    'Stock': '22',
    'Maintaining': '5 bottles',
    'Critical': '3',
    'Total Quantity': '22',
  },
  {
    'Product Name': 'Tarp 10oz 10.5ft',
    'QC Code': 'Otarp1010.5',
    'Stock': '1812',
    'Maintaining': '120 rolls',
    'Critical': '60',
    'Total Quantity': '1812',
  },
  {
    'Product Name': 'Tarp 10oz 6.5ft',
    'QC Code': 'OTarp10oz6.6x164',
    'Stock': '2',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '2',
  },
  {
    'Product Name': 'Tarp 10oz 8.2ft',
    'QC Code': 'OTarp10oz8.2X164',
    'Stock': '808',
    'Maintaining': '10 rolls',
    'Critical': '5',
    'Total Quantity': '808',
  },
  {
    'Product Name': 'Tarp 10oz 9.5ft',
    'QC Code': 'oTarp10oz9.5',
    'Stock': '805',
    'Maintaining': '5 rolls ',
    'Critical': '3',
    'Total Quantity': '805',
  },
  {
    'Product Name': 'Tarp 12oz 10.5ft',
    'QC Code': 'Otarp1210.5',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Tarp 12oz 6.2ft',
    'QC Code': 'Otarp126.2',
    'Stock': '1',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '1',
  },
  {
    'Product Name': 'Tarp 13oz 10.5ft',
    'QC Code': 'Otarp1310.5',
    'Stock': '714',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '714',
  },
  {
    'Product Name': 'Tarp 13oz 9.2ft',
    'QC Code': 'Otarp139.2 x 50m',
    'Stock': '84',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '84',
  },
  {
    'Product Name': 'Tarp 13oz 9.5ft',
    'QC Code': 'Otarp139.5',
    'Stock': '22',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '22',
  },
  {
    'Product Name': 'Tarp 13oz Matte 10.5ft',
    'QC Code': 'Otarp13omtt10.5x50m',
    'Stock': '11',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '11',
  },
  {
    'Product Name': 'Tarp 13oz Matte 8.2ft',
    'QC Code': 'Otarp13omtt8.2x50m',
    'Stock': '5',
    'Maintaining': 'pr',
    'Critical': '0',
    'Total Quantity': '5',
  },
  {
    'Product Name': 'Tissue',
    'QC Code': 'Otissue',
    'Stock': '117',
    'Maintaining': '20 pcs',
    'Critical': '10',
    'Total Quantity': '117',
  },
];

final List<Map<String, String>> kInventoryTrackerSeedRows =
    _kInventoryTrackerLegacySeedRows.map((row) {
  final legacy = (row['Maintaining'] ?? '').trim();
  String qty = '';
  String unit = '';
  if (legacy.isNotEmpty) {
    final lower = legacy.toLowerCase();
    if (lower == 'pr' || lower == 'per request' || lower == 'per-request') {
      qty = '-';
      unit = 'PR';
    } else {
      final cleaned = legacy.replaceAll(',', '');
      final m = RegExp(r'^(-?\d+(?:\.\d+)?)(?:\s+(.+))?$').firstMatch(cleaned);
      if (m != null) {
        qty = (m.group(1) ?? '').trim();
        unit = (m.group(2) ?? '').trim();
      }
    }
  }

  final out = <String, String>{...row};
  out.remove('Maintaining');
  out['Maintaining Qty'] = qty;
  out['Maintaining Unit'] = unit;
  return out;
}).toList(growable: false);
